package com.example.assamplanetoriumscanner.model

data class ScannedTicket(
    val id: Int,
    val visitor_id: Int?,
    val booking_no: String,
    val visitor_name: String?,
    val mobile_no: String,
    val email_id: String?,
    val visiting_date: String,
    val general: Int,
    val student: Int,
    val nationality: String?,
    val t_person: Int,
    val show_time: Int,
    val is_student: Int,
    val net_amt: Double,
    val service_amt: Double,
    val gst_amt: Double?,
    val total_amt: Double,
    val status: Int,
    val cancel_request: Int,
    val cancel_requested_at: String?,
    val booking_payment_id: Int?,
    val paid_at: String,
    val is_web: Int,
    val step: Int,
    val created_by: Int,
    val created_at: String,
    val updated_at: String,
    val tnx_id: String,
    val order_id: String,
    val payment_gateway: Int
)